# This param set the maximum obstacle range. 
obstacle_range: 2.0 # 3.0

# This param helps robot 99
# To clear out space in front of it upto 3.0 meters away given a sensor reading
raytrace_range: 2.5 # 3.5

footprint: [[-0.2, -0.13], [-0.2, 0.13], [0.06, 0.13], [0.06, -0.13]]
# robot_radius: 0.2 # distance a circular robot should be clear of the obstacle
cost_scaling_factor: 1.5 # exponential rate at which the obstacle cost drops off (default: 10)
# inflation_radius: 0.40  # Default: 0.55, The radius in meters to which the map inflates obstacle cost values.
inflation_radius: 0.2
# max. distance from an obstacle at which costs are incurred for planning paths.

observation_sources: scan
# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
scan: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}

map_type: costmap #new