# static_map - True if using existing map
global_costmap:
  global_frame: map
  robot_base_frame: base_frame
  
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5
  static_map: true

  # plugins:
  # - {names: static,                      type: "costmap_2d::StaticLayer"}
  # - {names: obstacles_layer,             type: "costmap_2d::VoxelLayer"}
  # - {names: inflation_layer,             type: "costmap_2d::InflationLayer"}
  