local_costmap:
  global_frame: map
  robot_base_frame: base_frame
  
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5 
  
  static_map: false
  rolling_window: true
  width: 2.0
  height: 2.0
  resolution: 0.05

  # padding is 0.1 by default,making difficult to pass through narrow places  
  # footprint_padding: 0.0

  # plugins:
  # - {names: obstacles_layer,             type: "costmap_2d::ObstacleLayer"}
  # - {names: inflation_layer,             type: "costmap_2d::InflationLayer"}